Update IncomeDependentUtilityOfMoneyPersonScoringParameters.java (#1679)
* Update IncomeDependentUtilityOfMoneyPersonScoringParameters.java

There is some problem casting String into Double in the original way. I have made some changes. I don't know if there is other way to do this.

ClassCastException: class String cannot be cast to class Double (String and Double are in module java.base of loader 'bootstrap')

* Adding set/get person income in the Person Utils

* Change from double to Double, so that null value can be returned when attribute does not present

* Update IncomeDependentUtilityOfMoneyPersonScoringParameters.java

Change to concurrent HashMap to solve for multi threading problem

Co-authored-by: rakow <rakow@users.noreply.github.com>